version: "3.8"

services:
  # Node.js应用服务
  mysqlupdate-task:
    build: .
    container_name: mysqlupdate-task
    restart: unless-stopped
    ports:
      - "${PORT:-33000}:${PORT:-33000}"
    env_file:
      - .env
    environment:
      # 其他配置
      TZ: Asia/Shanghai
    networks:
      - mysqlupdate-network
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-33000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  mysqlupdate-network:
    driver: bridge
