-- 创建测试企业数据
-- 用于多租户数据库自动升级工具测试

-- 首先创建企业表（如果不存在）
CREATE TABLE IF NOT EXISTS `qc_enterprise` (
  `enterprise_id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `enterprise_key` varchar(255) NOT NULL COMMENT '企业KEY',
  `enterprise_code` int NOT NULL COMMENT '企业编号(六位数字编号)',
  `enterprise_name` varchar(255) DEFAULT NULL COMMENT '企业名称',
  `enterprise_logo` varchar(255) DEFAULT NULL COMMENT '企业logo',
  `database_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'enterprise' COMMENT '数据库名称',
  `database_hostname` varchar(255) NOT NULL DEFAULT '127.0.0.1',
  `database_username` varchar(255) NOT NULL DEFAULT 'root',
  `database_password` varchar(255) NOT NULL DEFAULT '123456',
  `database_hostport` varchar(255) NOT NULL DEFAULT '3306',
  `log_database_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'log_name' COMMENT '日志数据库名称',
  `log_database_hostname` varchar(255) DEFAULT '127.0.0.1',
  `log_database_username` varchar(255) DEFAULT 'root',
  `log_database_password` varchar(255) DEFAULT '123456',
  `log_database_hostport` varchar(255) DEFAULT '3306',
  `order_database_name` varchar(255) DEFAULT 'order_name',
  `order_database_hostname` varchar(255) DEFAULT '127.0.0.1',
  `order_database_username` varchar(255) DEFAULT 'root',
  `order_database_password` varchar(255) DEFAULT '123456',
  `order_database_hostport` varchar(255) DEFAULT '3306',
  `static_database_name` varchar(255) DEFAULT 'static_name',
  `static_database_hostname` varchar(255) DEFAULT '127.0.0.1',
  `static_database_username` varchar(255) DEFAULT 'root',
  `static_database_password` varchar(255) DEFAULT '123456',
  `static_database_hostport` varchar(255) DEFAULT '3306',
  `user_id` varchar(255) DEFAULT NULL COMMENT '企业归属用户ID',
  `status` tinyint NOT NULL DEFAULT '2' COMMENT '企业状态（2审核中1正常0禁用）',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`enterprise_id`),
  UNIQUE KEY `qc_enterprise_pk_2` (`enterprise_key`),
  UNIQUE KEY `qc_enterprise_pk_3` (`enterprise_code`),
  UNIQUE KEY `qc_enterprise_pk` (`database_name`),
  KEY `qc_enterprise_status_index` (`status`),
  KEY `qc_enterprise_enterprise_name_index` (`enterprise_name`),
  KEY `qc_enterprise_user_id_index` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='企业表';

-- 插入测试企业数据
INSERT INTO `qc_enterprise` (
  `enterprise_key`, 
  `enterprise_code`, 
  `enterprise_name`, 
  `enterprise_logo`,
  `database_name`, 
  `database_hostname`, 
  `database_username`, 
  `database_password`, 
  `database_hostport`,
  `log_database_name`,
  `log_database_hostname`,
  `log_database_username`,
  `log_database_password`,
  `log_database_hostport`,
  `order_database_name`,
  `order_database_hostname`,
  `order_database_username`,
  `order_database_password`,
  `order_database_hostport`,
  `static_database_name`,
  `static_database_hostname`,
  `static_database_username`,
  `static_database_password`,
  `static_database_hostport`,
  `user_id`,
  `status`, 
  `create_time`, 
  `update_time`
) VALUES 
-- 测试企业1：使用默认配置
(
  'test_enterprise_001', 
  100001, 
  '测试企业001', 
  NULL,
  'test_enterprise_001', 
  'localhost', 
  'root', 
  '123456', 
  '3306',
  'test_enterprise_001_log',
  'localhost',
  'root',
  '123456',
  '3306',
  'test_enterprise_001_order',
  'localhost',
  'root',
  '123456',
  '3306',
  'test_enterprise_001_static',
  'localhost',
  'root',
  '123456',
  '3306',
  'admin_001',
  1, 
  NOW(), 
  NOW()
),
-- 测试企业2：使用不同的数据库配置
(
  'test_enterprise_002', 
  100002, 
  '测试企业002', 
  NULL,
  'test_enterprise_002', 
  'localhost', 
  'root', 
  '123456', 
  '3306',
  'test_enterprise_002_log',
  'localhost',
  'root',
  '123456',
  '3306',
  'test_enterprise_002_order',
  'localhost',
  'root',
  '123456',
  '3306',
  'test_enterprise_002_static',
  'localhost',
  'root',
  '123456',
  '3306',
  'admin_002',
  1, 
  NOW(), 
  NOW()
),
-- 测试企业3：模拟多门店连锁企业
(
  'chain_store_001', 
  200001, 
  '连锁门店企业', 
  NULL,
  'chain_store_001', 
  'localhost', 
  'root', 
  '123456', 
  '3306',
  'chain_store_001_log',
  'localhost',
  'root',
  '123456',
  '3306',
  'chain_store_001_order',
  'localhost',
  'root',
  '123456',
  '3306',
  'chain_store_001_static',
  'localhost',
  'root',
  '123456',
  '3306',
  'chain_admin',
  1, 
  NOW(), 
  NOW()
);

-- 查看插入的企业数据
SELECT 
  enterprise_id,
  enterprise_key,
  enterprise_code,
  enterprise_name,
  database_name,
  status,
  create_time
FROM qc_enterprise 
WHERE status = 1 
ORDER BY enterprise_id;

-- 显示企业总数
SELECT 
  COUNT(*) as total_enterprises,
  COUNT(CASE WHEN status = 1 THEN 1 END) as active_enterprises,
  COUNT(CASE WHEN status = 0 THEN 1 END) as disabled_enterprises,
  COUNT(CASE WHEN status = 2 THEN 1 END) as pending_enterprises
FROM qc_enterprise; 